# Generated by Django 4.2.7 on 2024-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_location_one_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_one_latitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_one_longitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_two_latitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_two_longitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
