# Generated by Django 4.2.7 on 2024-02-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_count_down_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='count_down_timer',
        ),
    ]
